apiVersion: v1
kind: Service
metadata:
  name: iris-ml-service
spec:
  # LoadBalancer automatically provisions a public IP on GCP!
  type: LoadBalancer
  selector:
    app: iris-ml-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
